az devops configure --defaults organization=https://dev.azure.com/cegid project=AI CoE


REM PAT: 4ZhaLscQ8ebEUqvbcyS3SPIhDleBLtMC1ppVWYmsvUdgPzzn7XiVJQQJ99BFACAAAAA3CBh8AAASAZDO36tr
REM PAT: 4ZhaLscQ8ebEUqvbcyS3SPIhDleBLtMC1ppVWYmsvUdgPzzn7XiVJQQJ99BFACAAAAA3CBh8AAASAZDO36tr